server:
  contextPath: /
  port: 8088


spring:
  output:
    ansi:
      enabled: never

##jpa 使用
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
      platform: mysql
      url: jdbc:mysql://local:3306/xxxxxdb?useUnicode=true&characterEncoding=UTF-8
      username: dddd
      password: aaaaa
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            ##设置连接超时时间 10秒
            timeoutInMilliseconds: 10000
cn:
  fintecher:
    organize:
      core:
        url: http://localhost:8087