server:
  contextPath: /
  port: 8082

spring:
  output:
    ansi:
      enabled: never

  rabbitmq:
    host: 10.10.1.71
    port: 5672
    username: xxx
    password: xxx
    virtual-host: /xxx
    listener:
      concurrency: 4
      max-concurrency: 4
      retry:
       enabled: true

  redis:
    database: 0
    host: redis
    port: 6379
    password:
    max-active: 8
    pool:
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            ##设置连接超时时间 10秒
            timeoutInMilliseconds: 100000
cn:
  fintecher:
    organize:
      core:
        url: http://localhost:8087

loan:
  manager:
    core:
      url: http://lmcore:8081
    service:
      url: http://lmservice:8082

file:
  service:
    url: http://172.16.10.206:9091

authorization:
  service:
      url: http://authservice:8090/authorization-service

remoteTokenServices:
  clientId: my-trusted-client-with-secret
  clientSecret: somesecret
  checkTokenEndpointUrl: http://authservice:8090/authorization-service/oauth/check_token
  tokenEndpointUrl: http://authservice:8090/authorization-service/oauth/token
  revokeTokenUrl: http://authservice:8090/authorization-service/oauth/revoke_token


#注册中心配置
eureka:
  client:
    serviceUrl:
       defaultZone: http://eurekaserver:8001/eureka
